/**
 * @description       : 
 * @author            : Charush Devgan
 * @group             : 
 * @last modified on  : 06.21.2023
 * @last modified by  : Charush Devgan 
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   06.21.2023   Charush Devgan   Initial Version
**/
public with sharing class TOSC_DemoClass {
    public TOSC_DemoClass() {
        System.debug('Deployed!!');
    }
}